### ISSUE TITLE
ENDPOINT_NAME redefined in many example files

### ISSUE THREAD

**Issue by joaocc** [Azure/azureml-examples#1284]
## Which example? Describe the issue
In many example files, it seems that ENDPOINT_NAME is being defined twice

`cli/deploy-tfserving.sh` or `cli/deploy-safe-rollout-k8s-online-endpoints.sh`` or ...
```
# <set_endpoint_name>
export ENDPOINT_NAME="tfservtest"
# </set_endpoint_name>

export ENDPOINT_NAME=endpt-tfserving-`echo $RANDOM`
```

I tried looking for information on whether this was a convention, or there was some practical reason for that, but could not find it. While this is not a big issue (the 1st assignment will be overwrite) I feel it may be a bit confusing.
For reference, this seems to have been introduced in https://github.com/Azure/azureml-examples/pull/890

**Comment by lostmygithubaccount** [comment]
The underlying reason for this is endpoint names need to be unique. For an actual user, this isn't a huge deal -- you'll pick an endpoint name, and get a clear error if you try to re-use it. However for automating the running of the examples in this repository, those naming conflicts can cause issues -- if the same example is running in an action at the same time, or a previous one fails and doesn't delete the endpoint, etc. 

So to keep the names clean for the doc snippets, you'll see a more normal name within the HTML snippets (those get pulled out into docs.microsoft.com) and then overwritten write after with a random string for automation.

**Comment by joaocc** [comment]
The uniqueness of endpoints makes all the sense in the world. My only doubt was in the redefinition of the variable on the same script. I missed the fact that the <> snippets were to be sent to documentation.
Thanks for the clarification
